# Forge
name: GitHub-Buttons
author: andidittrich
category: Interface
tags: [github, buttons, stars, stargazers, forks, watchers]
demo: http://github-buttons.andidittrich.de
docs: http://github-buttons.andidittrich.de
current: v2.2